nfd:
  enabled: false

labeller:
  enabled: true

dp:
  image:
    repository: docker.io/rocm/k8s-device-plugin
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.31.0.0"
  resources: {}

lbl:
  image:
    repository: docker.io/rocm/k8s-device-plugin
    tag: "labeller-1.31.0.0"
  resources: {}

imagePullSecrets: []

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: platform.neuromation.io/job
    operator: Exists
    effect: NoSchedule
  - key: "amd.com/gpu"
    operator: Exists
    effect: NoSchedule

node_selector_enabled: true
node_selector:
  feature.node.kubernetes.io/amd-gpu: "true"
